var buttonColors = ["red","blue","green","yellow"];
var gamePattern = [];                               //to hold the pattern generated by the game
var userClickedPattern = [];                        //to hold pattern clicked by user
var started = false;                                //to keep a track whether the game has started or not
var level = 0;                                      //at the start, the level will be set to 0



//When keyboard key is pressed for first time, calling nextSequence();
$(document).keypress(function(){
    if(!started){                                       //started = false
        $("#level-title2").text("Level " + level);
        nextSequence();
        started = true;
    }
});

function nextSequence(){
    userClickedPattern = [];
    level++;
    $("#level-title2").text("Level " + level);               //updating h1

    //Below Code for system to choose random color sequence
    var randomNum = Math.floor(Math.random() * 4);          //to generate random variable between 0-3
    var randomChosenColor = buttonColors[randomNum];
    gamePattern.push(randomChosenColor);                    //to push the elements randomly selected in gamePattern array
    $("#" + randomChosenColor).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomChosenColor);                           //to play sound upon choosing random color
}




//For registering the input by user
$(".btn").click(function(){
    var userChosenColor = $(this).attr("id");
    userClickedPattern.push(userChosenColor);   //storing th einput in array
    playSound(userChosenColor);
    animatePress(userChosenColor);

    checkAnswer(userClickedPattern.length - 1);
})




//function to check answer
function checkAnswer(currentLevel){
    if(gamePattern[currentLevel] === userClickedPattern[currentLevel]){         //if both sequence match
        if(userClickedPattern.length === gamePattern.length){                   //to check whether the sequence has finished or not

            setTimeout(function(){                                              //to again call equence after a delay of 1 sec
                nextSequence();
            }, 1000);
        }
    }
    else{
        playSound("wrong");        
        
        //to add class of "game-over" defined in styles.css file
        $("body").addClass("game-over");

        setTimeout(function(){                      //to remove game-over class after 200 milliSeconds
            $("body").removeClass("game-over");
        }, 200);

        //to change h1 text after game-over
        $("#level-title2").text("Game Over, Press any Key to Restart");

        satrtOver();        
    }
}



//For ANIMATION
function animatePress(currentColor){
    $("#" + currentColor).addClass("pressed");

    setTimeout(function(){
        $("#" + currentColor).removeClass("pressed");
    }, 100);
}



//For SOUND
function playSound(name){
    var audio = new Audio("sounds/" + name + ".mp3");
    audio.play();
}


//To RESTART the GAME
function satrtOver(){
    level = 0;
    gamePattern = [];               //game pattern resets inside the system
    started = false;
}
